version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  block-watcher:
    build: ./block-watcher

  swap-recorder:
    build: ./swap-recorder
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      SHARED_DIRECTORY: "${SHARED_DIRECTORY}"
    volumes:
      - ./data:/app/data

  price-recorder:
    build: ./price-recorder
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      SHARED_DIRECTORY: "${SHARED_DIRECTORY}"
    volumes:
      - ./data:/app/data

  liquidity-recorder:
    build: ./liquidity-recorder
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      SHARED_DIRECTORY: "${SHARED_DIRECTORY}"
    volumes:
      - ./data:/app/data

  api:
    build: ./api
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      SHARED_DIRECTORY: "${SHARED_DIRECTORY}"
    volumes:
      - ./data:/app/data
