version: "3"

services:
  db:
    image: postgres
    ports:
      - "4321:5432"
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "master"
      POSTGRES_DB: "plenty"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  block-watcher:
    build: ./block-watcher

  swap-recorder:
    build: ./swap-recorder
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data:/app/data
