version: "2.1"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "${PG_VOLUME_DIR}:/var/lib/postgresql/data"

  block-watcher:
    build: ./block-watcher
    ports:
      - "6024:6024"
    environment:
      TEZOS_RPC_URL: "${TEZOS_RPC_URL}"

  aggregate-recorder:
    build: ./aggregate-recorder
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      TZKT_URL: "${TZKT_URL}"
      DATA_TTL: "${DATA_TTL}"
      CONFIG_URL: "${CONFIG_URL}"
      TEZ_CTEZ_POOL: "${TEZ_CTEZ_POOL}"
      INDEXING_START: "${INDEXING_START}"

  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      CONFIG_URL: "${CONFIG_URL}"
