version: "2.1"

services:
  block-watcher:
    build: ./block-watcher
    ports:
      - "6024:6024"
    environment:
      TEZOS_RPC_URL: "${TEZOS_RPC_URL}"
  aggregate-recorder:
    build: ./recorder
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      TZKT_URL: "${TZKT_URL}"
      DATA_TTL: "${DATA_TTL}"
      TEZ_CTEZ_POOL: "${TEZ_CTEZ_POOL}"
      INDEXING_START: "${INDEXING_START}"
    volumes:
      - ./data:/data
